# Generated by Django 3.0.3 on 2020-02-24 06:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
