# Generated by Django 3.0.3 on 2020-03-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200224_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_path',
            field=models.TextField(null=True),
        ),
    ]
