# Generated by Django 3.0.3 on 2020-03-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_img_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_path',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
